version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: betting-api-postgres
    environment:
      POSTGRES_DB: betting
      POSTGRES_USER: betting
      POSTGRES_PASSWORD: betting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
