services:
  betting-api-postgres:
    image: postgres:17
    container_name: betting-api-postgres
    environment:
      POSTGRES_DB: betting
      POSTGRES_USER: betting
      POSTGRES_PASSWORD: betting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  betting-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betting-api
    depends_on:
      betting-api-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://betting-api-postgres:5432/betting
      SPRING_DATASOURCE_USERNAME: betting
      SPRING_DATASOURCE_PASSWORD: betting
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local